from __future__ import annotations

from typing import Union
from typing_extensions import TypeAlias

from .beta_managed_agents_multiagent20261001_params import BetaManagedAgentsMultiagent20261001Params
from .beta_managed_agents_multiagent_coordinator_params import BetaManagedAgentsMultiagentCoordinatorParams

__all__ = ["BetaManagedAgentsMultiagentParams"]

BetaManagedAgentsMultiagentParams: TypeAlias = Union[
    BetaManagedAgentsMultiagentCoordinatorParams, BetaManagedAgentsMultiagent20261001Params
]
