from .beta_browser_triple_click_tool_use_block import BetaBrowserTripleClickToolUseBlock

__all__ = ["BetaResponseBrowserTripleClickToolUseBlock"]

BetaResponseBrowserTripleClickToolUseBlock = BetaBrowserTripleClickToolUseBlock
"""
BetaResponseBrowserTripleClickToolUseBlock has been renamed to BetaBrowserTripleClickToolUseBlock
"""
