from .beta_computer_left_mouse_up_tool_use_block import BetaComputerLeftMouseUpToolUseBlock

__all__ = ["BetaResponseComputerLeftMouseUpToolUseBlock"]

BetaResponseComputerLeftMouseUpToolUseBlock = BetaComputerLeftMouseUpToolUseBlock
"""
BetaResponseComputerLeftMouseUpToolUseBlock has been renamed to BetaComputerLeftMouseUpToolUseBlock
"""
