from .beta_computer_right_click_tool_use_block import BetaComputerRightClickToolUseBlock

__all__ = ["BetaResponseComputerRightClickToolUseBlock"]

BetaResponseComputerRightClickToolUseBlock = BetaComputerRightClickToolUseBlock
"""
BetaResponseComputerRightClickToolUseBlock has been renamed to BetaComputerRightClickToolUseBlock
"""
