from .beta_browser_get_page_text_tool_use_block import BetaBrowserGetPageTextToolUseBlock

__all__ = ["BetaResponseBrowserGetPageTextToolUseBlock"]

BetaResponseBrowserGetPageTextToolUseBlock = BetaBrowserGetPageTextToolUseBlock
"""
BetaResponseBrowserGetPageTextToolUseBlock has been renamed to BetaBrowserGetPageTextToolUseBlock
"""
