# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Union
from typing_extensions import TypeAlias

from .beta_managed_agents_bash_tool_config_params import BetaManagedAgentsBashToolConfigParams
from .beta_managed_agents_edit_tool_config_params import BetaManagedAgentsEditToolConfigParams
from .beta_managed_agents_glob_tool_config_params import BetaManagedAgentsGlobToolConfigParams
from .beta_managed_agents_grep_tool_config_params import BetaManagedAgentsGrepToolConfigParams
from .beta_managed_agents_read_tool_config_params import BetaManagedAgentsReadToolConfigParams
from .beta_managed_agents_write_tool_config_params import BetaManagedAgentsWriteToolConfigParams
from .beta_managed_agents_web_fetch_tool_config_params import BetaManagedAgentsWebFetchToolConfigParams
from .beta_managed_agents_web_search_tool_config_params import BetaManagedAgentsWebSearchToolConfigParams

__all__ = ["BetaManagedAgentsAgentToolConfigParams"]

BetaManagedAgentsAgentToolConfigParams: TypeAlias = Union[
    BetaManagedAgentsBashToolConfigParams,
    BetaManagedAgentsEditToolConfigParams,
    BetaManagedAgentsReadToolConfigParams,
    BetaManagedAgentsWriteToolConfigParams,
    BetaManagedAgentsGlobToolConfigParams,
    BetaManagedAgentsGrepToolConfigParams,
    BetaManagedAgentsWebFetchToolConfigParams,
    BetaManagedAgentsWebSearchToolConfigParams,
]
