from .beta_computer_screenshot_tool_use_block import BetaComputerScreenshotToolUseBlock

__all__ = ["BetaResponseComputerScreenshotToolUseBlock"]

BetaResponseComputerScreenshotToolUseBlock = BetaComputerScreenshotToolUseBlock
"""
BetaResponseComputerScreenshotToolUseBlock has been renamed to BetaComputerScreenshotToolUseBlock
"""
