from .beta_browser_middle_click_tool_use_block import BetaBrowserMiddleClickToolUseBlock

__all__ = ["BetaResponseBrowserMiddleClickToolUseBlock"]

BetaResponseBrowserMiddleClickToolUseBlock = BetaBrowserMiddleClickToolUseBlock
"""
BetaResponseBrowserMiddleClickToolUseBlock has been renamed to BetaBrowserMiddleClickToolUseBlock
"""
