from typing_extensions import Literal, TypeAlias

__all__ = ["BetaManagedAgentsSessionEventType"]

BetaManagedAgentsSessionEventType: TypeAlias = Literal[
    "user.message",
    "user.interrupt",
    "user.tool_confirmation",
    "user.custom_tool_result",
    "agent.custom_tool_use",
    "agent.message",
    "agent.thinking",
    "agent.mcp_tool_use",
    "agent.mcp_tool_result",
    "agent.tool_use",
    "agent.tool_result",
    "agent.thread_message_received",
    "agent.thread_message_sent",
    "agent.thread_context_compacted",
    "session.error",
    "session.status_rescheduled",
    "session.status_running",
    "session.status_idle",
    "session.status_terminated",
    "session.thread_created",
    "span.outcome_evaluation_start",
    "span.outcome_evaluation_end",
    "span.model_request_start",
    "span.model_request_end",
    "span.outcome_evaluation_ongoing",
    "user.define_outcome",
    "session.thread_status_running",
    "session.thread_status_idle",
    "session.thread_status_terminated",
    "user.tool_result",
    "session.thread_status_rescheduled",
    "session.updated",
    "system.message",
    "session.usage",
]
