#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ] && [ "$SKIP_BREW" != "1" ]; then
  brew bundle check >/dev/null 2>&1 || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

echo "==> Installing Python…"
uv python install

echo "==> Installing Python dependencies…"
uv sync --all-extras

echo "==> Exporting Python dependencies…"
# note: `--no-hashes` is required because of https://github.com/pypa/pip/issues/4995
uv export -o requirements-dev.lock --no-hashes
