#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Running ruff"
uv run ruff check .

echo "==> Running pyright"
uv run pyright

echo "==> Running mypy"
uv run mypy .

echo "==> Making sure it imports"
uv run python -c 'import anthropic'
