# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

"""
Resource base classes used by the Anthropic SDK.

These classes provide the foundational GET/POST/PATCH/PUT/DELETE bindings
for synchronous and asynchronous resources generated by Stainless.
"""

from __future__ import annotations

import time

import anyio

from ._base_client import SyncAPIClient, AsyncAPIClient


class SyncAPIResource:
    """Base class for all synchronous API resources."""

    _client: SyncAPIClient

    def __init__(self, client: SyncAPIClient) -> None:
        self._client = client
        self._get = client.get
        self._post = client.post
        self._patch = client.patch
        self._put = client.put
        self._delete = client.delete
        self._get_api_list = client.get_api_list

    def _sleep(self, seconds: float) -> None:
        """Sleep for a number of seconds synchronously."""
        time.sleep(seconds)


class AsyncAPIResource:
    """Base class for all asynchronous API resources."""

    _client: AsyncAPIClient

    def __init__(self, client: AsyncAPIClient) -> None:
        self._client = client
        self._get = client.get
        self._post = client.post
        self._patch = client.patch
        self._put = client.put
        self._delete = client.delete
        self._get_api_list = client.get_api_list

    async def _sleep(self, seconds: float) -> None:
        """Sleep for a number of seconds asynchronously."""
        await anyio.sleep(seconds)
