from .computer_cursor_position_tool_use_block import ComputerCursorPositionToolUseBlock

__all__ = ["ResponseComputerCursorPositionToolUseBlock"]

ResponseComputerCursorPositionToolUseBlock = ComputerCursorPositionToolUseBlock
"""
ResponseComputerCursorPositionToolUseBlock has been renamed to ComputerCursorPositionToolUseBlock
"""
