# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SignatureDelta"]


class SignatureDelta(BaseModel):
    signature: str
    """
    The `signature` for this thinking block: an opaque value used to verify that the
    block was generated by Claude when it is passed back to the API. Delivered in a
    `signature_delta` event just before the block's `content_block_stop` event.
    """

    type: Literal["signature_delta"]
