# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["ThinkingBlock"]


class ThinkingBlock(BaseModel):
    signature: str
    """
    A value used to verify that this thinking block was generated by Claude when it
    is passed back to the API.

    This is an opaque field and should not be interpreted or parsed. When passing
    thinking blocks back to the API (required when using tools with extended
    thinking), pass them back exactly as received, with this field intact.

    See
    [extended thinking](https://platform.claude.com/docs/en/build-with-claude/extended-thinking)
    for details.
    """

    thinking: str
    """The text of Claude's thinking process for this block."""

    type: Literal["thinking"]
