# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ThinkingBlockParam"]


class ThinkingBlockParam(TypedDict, total=False):
    signature: Required[str]
    """
    The `signature` value of this thinking block, exactly as returned by the API in
    a previous response. Used to verify that the block was generated by Claude.

    Thinking blocks must be passed back unmodified and in their original order; a
    modified block results in a 400 `invalid_request_error`.
    """

    thinking: Required[str]
    """The `thinking` text of this block as returned by the API."""

    type: Required[Literal["thinking"]]
