name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  pr_title:
    name: Validate PR title
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'anthropics/anthropic-sdk-python'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
